version: '3.8'

services:
  # Demo Flask application
  web:
    build: .
    ports:
      - "3008:3008"
    volumes:
      - .:/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3008/"]
      interval: 30s
      timeout: 10s
      retries: 3
    container_name: dast-demo-app

  # ZAP DAST scanner - baseline scan
  zap-baseline:
    image: ghcr.io/zaproxy/zaproxy:stable
    command: 
      - zap-baseline.py
      - -t
      - http://host.docker.internal:3008
      - -J
      - /zap/wrk/zap_report.json
    volumes:
      - ./zap_output:/zap/wrk:rw
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - ZAP_IGNORED_URLS=^https?://host\.docker\.internal:3000/api.*
    depends_on:
      - web
    profiles:
      - baseline

  # ZAP DAST scanner - full scan
  zap-full:
    image: ghcr.io/zaproxy/zaproxy:stable
    command: 
      - zap-full-scan.py
      - -t
      - http://host.docker.internal:3008
      - -J
      - /zap/wrk/zap_report.json
    volumes:
      - ./zap_output:/zap/wrk:rw
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - ZAP_IGNORED_URLS=^https?://host\.docker\.internal:3000/api.*
    depends_on:
      - web
    profiles:
      - full
