version: '3.8'

services:
  web:
    build: .
    ports:
      - "3008:3008"
    volumes:
      - .:/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3008/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
